"""initial schema

Revision ID: 397a42c378ab
Revises: 
Create Date: 2026-08-27 02:09:42.357655
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '397a42c378ab'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_number_sequences',
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_value', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('prefix', 'year', name=op.f('pk_case_number_sequences'))
    )
    op.create_table('case_types',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Enum('INVESTIGATION', 'DEATH_CLAIM', name='casecategory', native_enum=False, length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('import_aliases', sa.Text(), nullable=True),
    sa.Column('default_tat_days', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_types')),
    sa.UniqueConstraint('code', name=op.f('uq_case_types_code'))
    )
    op.create_table('companies',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=False),
    sa.Column('company_type', sa.Enum('BANK', 'INSURANCE', 'INVESTIGATION_CLIENT', 'OTHER', name='companytype', native_enum=False, length=32), nullable=False),
    sa.Column('import_aliases', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('pin_code', sa.String(length=12), nullable=True),
    sa.Column('contact_person', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('logo_path', sa.String(length=512), nullable=True),
    sa.Column('default_tat_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('code', name=op.f('uq_companies_code'))
    )
    op.create_table('departments',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('code', name=op.f('uq_departments_code'))
    )
    op.create_table('designations',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_designations')),
    sa.UniqueConstraint('code', name=op.f('uq_designations_code'))
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('module', sa.String(length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_module'), ['module'], unique=False)

    op.create_table('roles',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=24), nullable=True),
    sa.Column('staff_category', sa.Enum('FIELD', 'BACK_OFFICE', 'MANAGEMENT', name='staffcategory', native_enum=False, length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('login_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_logout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_is_active_staff_category', ['is_active', 'staff_category'], unique=False)
        batch_op.create_index('ix_users_last_activity_at', ['last_activity_at'], unique=False)

    op.create_table('app_settings',
    sa.Column('key', sa.String(length=96), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('group', sa.String(length=48), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_app_settings_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings')),
    sa.UniqueConstraint('key', name='uq_app_settings_key')
    )
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(length=200), nullable=True),
    sa.Column('action', sa.Enum('LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'PASSWORD_CHANGED', 'CASE_CREATED', 'CASE_IMPORTED', 'CASE_UPDATED', 'CASE_ASSIGNED', 'CASE_REASSIGNED', 'CASE_STATUS_CHANGED', 'CASE_DELETED', 'FORM_UPDATED', 'FORM_SUBMITTED', 'DOCUMENT_UPLOADED', 'DOCUMENT_DELETED', 'DOCUMENT_GENERATED', 'IMPORT_CREATED', 'IMPORT_COMMITTED', 'IMPORT_ROLLED_BACK', 'STAFF_CREATED', 'STAFF_UPDATED', 'STAFF_DISABLED', 'ROLE_CHANGED', 'PERMISSION_CHANGED', 'SETTINGS_CHANGED', 'COMPANY_CHANGED', 'TEMPLATE_CHANGED', 'EXPORT_RUN', 'DATA_PURGED', name='auditaction', native_enum=False, length=40), nullable=False),
    sa.Column('module', sa.String(length=48), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('entity_label', sa.String(length=255), nullable=True),
    sa.Column('old_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('new_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('request_method', sa.String(length=12), nullable=True),
    sa.Column('request_path', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_action', ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_actor_created', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('document_templates',
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('case_type_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'NEEDS_CONVERSION', name='documenttemplatestatus', native_enum=False, length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('original_path', sa.String(length=512), nullable=False),
    sa.Column('tagged_path', sa.String(length=512), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('placeholder_map', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_type_id'], ['case_types.id'], name=op.f('fk_document_templates_case_type_id_case_types'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_document_templates_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_document_templates_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_templates')),
    sa.UniqueConstraint('company_id', 'case_type_id', 'version', name='uq_document_templates_ccv')
    )
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.create_index('ix_document_templates_lookup', ['company_id', 'case_type_id', 'status'], unique=False)

    op.create_table('employees',
    sa.Column('employee_code', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('middle_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'UNDISCLOSED', name='gender', native_enum=False, length=16), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('mobile', sa.String(length=24), nullable=True),
    sa.Column('alternate_mobile', sa.String(length=24), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('pin_code', sa.String(length=12), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('designation_id', sa.Uuid(), nullable=True),
    sa.Column('reporting_manager_id', sa.Uuid(), nullable=True),
    sa.Column('staff_category', sa.Enum('FIELD', 'BACK_OFFICE', 'MANAGEMENT', name='staffcategory', native_enum=False, length=24), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('employment_status', sa.Enum('ACTIVE', 'PROBATION', 'NOTICE_PERIOD', 'RESIGNED', 'TERMINATED', 'ON_LEAVE', name='employmentstatus', native_enum=False, length=24), nullable=False),
    sa.Column('base_city', sa.String(length=120), nullable=True),
    sa.Column('base_state', sa.String(length=120), nullable=True),
    sa.Column('profile_photo_path', sa.String(length=512), nullable=True),
    sa.Column('id_proof_type', sa.String(length=48), nullable=True),
    sa.Column('id_proof_number', sa.String(length=64), nullable=True),
    sa.Column('id_proof_path', sa.String(length=512), nullable=True),
    sa.Column('bank_account_name', sa.String(length=120), nullable=True),
    sa.Column('bank_account_number', sa.String(length=48), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=24), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_employees_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], name=op.f('fk_employees_designation_id_designations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['employees.id'], name=op.f('fk_employees_reporting_manager_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_employees_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('employee_code', name='uq_employees_employee_code'),
    sa.UniqueConstraint('user_id', name=op.f('uq_employees_user_id'))
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index('ix_employees_department_designation', ['department_id', 'designation_id'], unique=False)

    op.create_table('form_templates',
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('case_type_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_type_id'], ['case_types.id'], name=op.f('fk_form_templates_case_type_id_case_types'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_form_templates_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_templates')),
    sa.UniqueConstraint('company_id', 'case_type_id', 'version', name='uq_form_templates_ccv')
    )
    with op.batch_alter_table('form_templates', schema=None) as batch_op:
        batch_op.create_index('ix_form_templates_lookup', ['company_id', 'case_type_id', 'is_active'], unique=False)

    op.create_table('import_templates',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('header_row', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=120), nullable=True),
    sa.Column('duplicate_key_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('fallback_duplicate_key_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_import_templates_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_templates')),
    sa.UniqueConstraint('code', name=op.f('uq_import_templates_code'))
    )
    op.create_table('login_attempts',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_attempts_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_login_attempts_email_created', ['email', 'created_at'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sa.Enum('CASE_ASSIGNED', 'CASE_REASSIGNED', 'DUE_DATE_APPROACHING', 'CASE_OVERDUE', 'CORRECTION_REQUESTED', 'CASE_APPROVED', 'CASE_COMPLETED', 'IMPORT_COMPLETED', 'SYSTEM', name='notificationtype', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_read_created', ['user_id', 'is_read', 'created_at'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('saved_filters',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('query', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_filters_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_filters')),
    sa.UniqueConstraint('user_id', 'scope', 'name', name='uq_saved_filters_user_name')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('device_label', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_user_sessions_user_active', ['user_id', 'is_active'], unique=False)

    op.create_table('attendance',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', 'WEEK_OFF', 'HOLIDAY', 'ON_LEAVE', 'FIELD_DUTY', name='attendancestatus', native_enum=False, length=24), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worked_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('derived_from_login', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendance_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance')),
    sa.UniqueConstraint('employee_id', 'work_date', name='uq_attendance_employee_date')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index('ix_attendance_work_date', ['work_date'], unique=False)

    op.create_table('form_sections',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=96), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_repeatable', sa.Boolean(), nullable=False),
    sa.Column('visible_when', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['form_templates.id'], name=op.f('fk_form_sections_template_id_form_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_sections')),
    sa.UniqueConstraint('template_id', 'key', name='uq_form_sections_template_key')
    )
    op.create_table('import_batches',
    sa.Column('batch_number', sa.String(length=32), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('relative_path', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'VALIDATING', 'VALIDATED', 'IMPORTING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', 'ROLLED_BACK', name='importbatchstatus', native_enum=False, length=32), nullable=False),
    sa.Column('detected_headers', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('applied_mapping', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('warning_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('imported_rows', sa.Integer(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back_by_id', sa.Uuid(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_import_batches_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rolled_back_by_id'], ['users.id'], name=op.f('fk_import_batches_rolled_back_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['import_templates.id'], name=op.f('fk_import_batches_template_id_import_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_import_batches_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches')),
    sa.UniqueConstraint('batch_number', name=op.f('uq_import_batches_batch_number'))
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index('ix_import_batches_checksum', ['checksum_sha256'], unique=False)
        batch_op.create_index('ix_import_batches_status_created', ['status', 'created_at'], unique=False)

    op.create_table('import_column_mappings',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('source_column', sa.String(length=160), nullable=False),
    sa.Column('source_aliases', sa.Text(), nullable=True),
    sa.Column('target_field', sa.String(length=64), nullable=False),
    sa.Column('data_type', sa.String(length=24), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('transform', sa.String(length=48), nullable=True),
    sa.Column('validation_rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['import_templates.id'], name=op.f('fk_import_column_mappings_template_id_import_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_column_mappings')),
    sa.UniqueConstraint('template_id', 'target_field', name='uq_import_mappings_template_field')
    )
    op.create_table('leave_records',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('leave_type', sa.Enum('CASUAL', 'SICK', 'EARNED', 'UNPAID', 'MATERNITY', 'PATERNITY', 'COMPENSATORY', name='leavetype', native_enum=False, length=24), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leavestatus', native_enum=False, length=16), nullable=False),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_remark', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_leave_records_approved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_leave_records_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_records'))
    )
    with op.batch_alter_table('leave_records', schema=None) as batch_op:
        batch_op.create_index('ix_leave_records_employee_from', ['employee_id', 'from_date'], unique=False)

    op.create_table('user_activity',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('activity_type', sa.String(length=32), nullable=False),
    sa.Column('page', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], name=op.f('fk_user_activity_session_id_user_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_activity_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_activity'))
    )
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.create_index('ix_user_activity_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('cases',
    sa.Column('case_number', sa.String(length=32), nullable=False),
    sa.Column('category', sa.Enum('INVESTIGATION', 'DEATH_CLAIM', name='casecategory', native_enum=False, length=24), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('case_type_id', sa.Uuid(), nullable=False),
    sa.Column('krn_no', sa.String(length=64), nullable=True),
    sa.Column('policy_number', sa.String(length=64), nullable=True),
    sa.Column('application_number', sa.String(length=64), nullable=True),
    sa.Column('life_assured_name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('pin_code', sa.String(length=12), nullable=True),
    sa.Column('received_month', sa.String(length=24), nullable=True),
    sa.Column('import_remark', sa.Text(), nullable=True),
    sa.Column('report_prepared_by', sa.String(length=160), nullable=True),
    sa.Column('external_reference', sa.String(length=96), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_number', sa.String(length=32), nullable=True),
    sa.Column('alternate_contact', sa.String(length=32), nullable=True),
    sa.Column('email_id', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=160), nullable=True),
    sa.Column('sum_assured', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('premium_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('risk_commencement_date', sa.Date(), nullable=True),
    sa.Column('nominee_name', sa.String(length=200), nullable=True),
    sa.Column('nominee_relation', sa.String(length=96), nullable=True),
    sa.Column('status', sa.Enum('IMPORTED', 'UNASSIGNED', 'ASSIGNED', 'ACCEPTED', 'WIP', 'FIELD_INVESTIGATION', 'DOCUMENTS_PENDING', 'RIP', 'REPORT_SUBMITTED', 'UNDER_REVIEW', 'CORRECTION_REQUIRED', 'VERIFIED', 'COMPLETED', 'REJECTED', 'CANCELLED', name='casestatus', native_enum=False, length=32), nullable=False),
    sa.Column('outcome', sa.Enum('POSITIVE', 'NEGATIVE', 'SUSPICIOUS', name='caseoutcome', native_enum=False, length=24), nullable=True),
    sa.Column('report_status', sa.Enum('INTERIM', 'FINAL', name='reportstatus', native_enum=False, length=16), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='casepriority', native_enum=False, length=16), nullable=False),
    sa.Column('outcome_reason', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_by_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('imported_aging_days', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.Uuid(), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_cases_assigned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_cases_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_type_id'], ['case_types.id'], name=op.f('fk_cases_case_type_id_case_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_cases_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_cases_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_cases_import_batch_id_import_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_cases_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases')),
    sa.UniqueConstraint('case_number', name='uq_cases_case_number')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index('ix_cases_application_number', ['application_number'], unique=False)
        batch_op.create_index('ix_cases_assigned_status', ['assigned_to_id', 'status'], unique=False)
        batch_op.create_index('ix_cases_category_status', ['category', 'status'], unique=False)
        batch_op.create_index('ix_cases_company_krn', ['company_id', 'krn_no'], unique=False)
        batch_op.create_index('ix_cases_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index('ix_cases_due_at', ['due_at'], unique=False)
        batch_op.create_index('ix_cases_life_assured_name', ['life_assured_name'], unique=False)
        batch_op.create_index('ix_cases_policy_number', ['policy_number'], unique=False)
        batch_op.create_index('ix_cases_received_at', ['received_at'], unique=False)

    op.create_table('form_fields',
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('field_key', sa.String(length=96), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'TEXTAREA', 'NUMBER', 'CURRENCY', 'DATE', 'DATETIME', 'TIME', 'EMAIL', 'PHONE', 'SELECT', 'MULTI_SELECT', 'RADIO', 'CHECKBOX', 'BOOLEAN', 'YES_NO_NA', 'ADDRESS', 'FILE', 'IMAGE', 'SIGNATURE', 'TABLE', 'HEADING', name='fieldtype', native_enum=False, length=24), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('col_span', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('validation_rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('table_columns', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('source', sa.Enum('BANK_SUPPLIED', 'INVESTIGATION', 'SYSTEM', name='fieldsource', native_enum=False, length=24), nullable=False),
    sa.Column('prefill_from', sa.String(length=96), nullable=True),
    sa.Column('document_mapping', sa.String(length=96), nullable=True),
    sa.Column('is_readonly', sa.Boolean(), nullable=False),
    sa.Column('visible_when', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['form_sections.id'], name=op.f('fk_form_fields_section_id_form_sections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_fields')),
    sa.UniqueConstraint('section_id', 'field_key', name='uq_form_fields_section_key')
    )
    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.create_index('ix_form_fields_section_order', ['section_id', 'display_order'], unique=False)

    op.create_table('case_assignments',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_by_id', sa.Uuid(), nullable=True),
    sa.Column('previous_assignee_id', sa.Uuid(), nullable=True),
    sa.Column('is_reassignment', sa.Boolean(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='casepriority', native_enum=False, length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_case_assignments_assigned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_case_assignments_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_assignments_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_assignee_id'], ['users.id'], name=op.f('fk_case_assignments_previous_assignee_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_assignments'))
    )
    with op.batch_alter_table('case_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_case_assignments_case_created', ['case_id', 'created_at'], unique=False)

    op.create_table('case_documents',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.Enum('KYC', 'PHOTOGRAPH', 'MEDICAL', 'DEATH_CERTIFICATE', 'FIR_PMR', 'STATEMENT', 'INCOME_PROOF', 'AGE_PROOF', 'REPORT', 'OTHER', name='documentcategory', native_enum=False, length=32), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('relative_path', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geo_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('geo_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_documents_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_case_documents_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_documents'))
    )
    with op.batch_alter_table('case_documents', schema=None) as batch_op:
        batch_op.create_index('ix_case_documents_case_category', ['case_id', 'category'], unique=False)

    op.create_table('case_forms',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'SUBMITTED', 'CORRECTION_REQUIRED', 'APPROVED', name='caseformstatus', native_enum=False, length=32), nullable=False),
    sa.Column('completion_percent', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by_id', sa.Uuid(), nullable=True),
    sa.Column('correction_remark', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_forms_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('fk_case_forms_submitted_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['form_templates.id'], name=op.f('fk_case_forms_template_id_form_templates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_forms')),
    sa.UniqueConstraint('case_id', 'template_id', name='uq_case_forms_case_template')
    )
    op.create_table('case_notes',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_case_notes_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_notes_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_notes'))
    )
    with op.batch_alter_table('case_notes', schema=None) as batch_op:
        batch_op.create_index('ix_case_notes_case_created', ['case_id', 'created_at'], unique=False)

    op.create_table('case_status_history',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('previous_status', sa.Enum('IMPORTED', 'UNASSIGNED', 'ASSIGNED', 'ACCEPTED', 'WIP', 'FIELD_INVESTIGATION', 'DOCUMENTS_PENDING', 'RIP', 'REPORT_SUBMITTED', 'UNDER_REVIEW', 'CORRECTION_REQUIRED', 'VERIFIED', 'COMPLETED', 'REJECTED', 'CANCELLED', name='casestatus', native_enum=False, length=32), nullable=True),
    sa.Column('new_status', sa.Enum('IMPORTED', 'UNASSIGNED', 'ASSIGNED', 'ACCEPTED', 'WIP', 'FIELD_INVESTIGATION', 'DOCUMENTS_PENDING', 'RIP', 'REPORT_SUBMITTED', 'UNDER_REVIEW', 'CORRECTION_REQUIRED', 'VERIFIED', 'COMPLETED', 'REJECTED', 'CANCELLED', name='casestatus', native_enum=False, length=32), nullable=False),
    sa.Column('changed_by_id', sa.Uuid(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_status_history_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_case_status_history_changed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_status_history'))
    )
    with op.batch_alter_table('case_status_history', schema=None) as batch_op:
        batch_op.create_index('ix_case_status_history_case_created', ['case_id', 'created_at'], unique=False)

    op.create_table('case_timeline_events',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(length=200), nullable=True),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_case_timeline_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_timeline_events_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_timeline_events'))
    )
    with op.batch_alter_table('case_timeline_events', schema=None) as batch_op:
        batch_op.create_index('ix_case_timeline_case_occurred', ['case_id', 'occurred_at'], unique=False)

    op.create_table('death_claim_details',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('claimant_name', sa.String(length=200), nullable=True),
    sa.Column('claimant_relation', sa.String(length=96), nullable=True),
    sa.Column('claimant_age', sa.String(length=32), nullable=True),
    sa.Column('claimant_occupation', sa.String(length=160), nullable=True),
    sa.Column('claimant_income', sa.String(length=96), nullable=True),
    sa.Column('claimant_address', sa.Text(), nullable=True),
    sa.Column('claimant_contact', sa.String(length=32), nullable=True),
    sa.Column('date_of_death', sa.Date(), nullable=True),
    sa.Column('place_of_death', sa.String(length=255), nullable=True),
    sa.Column('cause_of_death', sa.String(length=255), nullable=True),
    sa.Column('type_of_death', sa.String(length=64), nullable=True),
    sa.Column('la_date_of_birth', sa.Date(), nullable=True),
    sa.Column('la_age', sa.String(length=32), nullable=True),
    sa.Column('la_occupation', sa.String(length=160), nullable=True),
    sa.Column('la_annual_income', sa.String(length=96), nullable=True),
    sa.Column('la_qualification', sa.String(length=120), nullable=True),
    sa.Column('la_marital_status', sa.String(length=48), nullable=True),
    sa.Column('standard_of_living', sa.String(length=64), nullable=True),
    sa.Column('death_certificate_verified', sa.Boolean(), nullable=True),
    sa.Column('death_certificate_remarks', sa.Text(), nullable=True),
    sa.Column('rti_applied', sa.Boolean(), nullable=True),
    sa.Column('rti_status', sa.String(length=120), nullable=True),
    sa.Column('profile_mismatch', sa.String(length=24), nullable=True),
    sa.Column('medical_non_disclosure', sa.String(length=24), nullable=True),
    sa.Column('death_before_issuance', sa.String(length=24), nullable=True),
    sa.Column('impersonation', sa.String(length=24), nullable=True),
    sa.Column('forged_documents', sa.String(length=24), nullable=True),
    sa.Column('nexus_involvement', sa.String(length=24), nullable=True),
    sa.Column('industry_shopping', sa.String(length=24), nullable=True),
    sa.Column('other_adverse_findings', sa.String(length=24), nullable=True),
    sa.Column('no_adverse_findings', sa.String(length=24), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_death_claim_details_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_death_claim_details')),
    sa.UniqueConstraint('case_id', name=op.f('uq_death_claim_details_case_id'))
    )
    op.create_table('generated_documents',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('template_version', sa.Integer(), nullable=True),
    sa.Column('output_format', sa.Enum('DOCX', 'PDF', name='generatedformat', native_enum=False, length=16), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('relative_path', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('generated_by_id', sa.Uuid(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_client_template', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_generated_documents_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], name=op.f('fk_generated_documents_generated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], name=op.f('fk_generated_documents_template_id_document_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_documents'))
    )
    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.create_index('ix_generated_documents_case_created', ['case_id', 'created_at'], unique=False)

    op.create_table('import_rows',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('parsed_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VALID', 'WARNING', 'ERROR', 'DUPLICATE', 'IMPORTED', 'SKIPPED', name='importrowstatus', native_enum=False, length=24), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('duplicate_of_case_id', sa.Uuid(), nullable=True),
    sa.Column('created_case_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_import_rows_batch_id_import_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_case_id'], ['cases.id'], name=op.f('fk_import_rows_created_case_id_cases'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_of_case_id'], ['cases.id'], name=op.f('fk_import_rows_duplicate_of_case_id_cases'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_rows')),
    sa.UniqueConstraint('batch_id', 'row_number', name='uq_import_rows_batch_row')
    )
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.create_index('ix_import_rows_batch_status', ['batch_id', 'status'], unique=False)

    op.create_table('case_field_values',
    sa.Column('case_form_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=True),
    sa.Column('field_key', sa.String(length=96), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('source', sa.Enum('BANK_SUPPLIED', 'INVESTIGATION', 'SYSTEM', name='fieldsource', native_enum=False, length=24), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.Uuid(), nullable=True),
    sa.Column('original_column', sa.String(length=120), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_form_id'], ['case_forms.id'], name=op.f('fk_case_field_values_case_form_id_case_forms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields.id'], name=op.f('fk_case_field_values_field_id_form_fields'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_case_field_values_import_batch_id_import_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_case_field_values_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_field_values')),
    sa.UniqueConstraint('case_form_id', 'field_key', name='uq_case_field_values_form_key')
    )
    with op.batch_alter_table('case_field_values', schema=None) as batch_op:
        batch_op.create_index('ix_case_field_values_form', ['case_form_id'], unique=False)

    op.create_table('case_field_value_history',
    sa.Column('case_field_value_id', sa.Uuid(), nullable=False),
    sa.Column('field_key', sa.String(length=96), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.Uuid(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_field_value_id'], ['case_field_values.id'], name=op.f('fk_case_field_value_history_case_field_value_id_case_field_values'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_case_field_value_history_changed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_field_value_history'))
    )
    with op.batch_alter_table('case_field_value_history', schema=None) as batch_op:
        batch_op.create_index('ix_case_field_value_history_value', ['case_field_value_id', 'changed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_field_value_history', schema=None) as batch_op:
        batch_op.drop_index('ix_case_field_value_history_value')

    op.drop_table('case_field_value_history')
    with op.batch_alter_table('case_field_values', schema=None) as batch_op:
        batch_op.drop_index('ix_case_field_values_form')

    op.drop_table('case_field_values')
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.drop_index('ix_import_rows_batch_status')

    op.drop_table('import_rows')
    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_generated_documents_case_created')

    op.drop_table('generated_documents')
    op.drop_table('death_claim_details')
    with op.batch_alter_table('case_timeline_events', schema=None) as batch_op:
        batch_op.drop_index('ix_case_timeline_case_occurred')

    op.drop_table('case_timeline_events')
    with op.batch_alter_table('case_status_history', schema=None) as batch_op:
        batch_op.drop_index('ix_case_status_history_case_created')

    op.drop_table('case_status_history')
    with op.batch_alter_table('case_notes', schema=None) as batch_op:
        batch_op.drop_index('ix_case_notes_case_created')

    op.drop_table('case_notes')
    op.drop_table('case_forms')
    with op.batch_alter_table('case_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_case_documents_case_category')

    op.drop_table('case_documents')
    with op.batch_alter_table('case_assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_case_assignments_case_created')

    op.drop_table('case_assignments')
    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.drop_index('ix_form_fields_section_order')

    op.drop_table('form_fields')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index('ix_cases_received_at')
        batch_op.drop_index('ix_cases_policy_number')
        batch_op.drop_index('ix_cases_life_assured_name')
        batch_op.drop_index('ix_cases_due_at')
        batch_op.drop_index('ix_cases_company_status')
        batch_op.drop_index('ix_cases_company_krn')
        batch_op.drop_index('ix_cases_category_status')
        batch_op.drop_index('ix_cases_assigned_status')
        batch_op.drop_index('ix_cases_application_number')

    op.drop_table('cases')
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.drop_index('ix_user_activity_user_created')

    op.drop_table('user_activity')
    with op.batch_alter_table('leave_records', schema=None) as batch_op:
        batch_op.drop_index('ix_leave_records_employee_from')

    op.drop_table('leave_records')
    op.drop_table('import_column_mappings')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index('ix_import_batches_status_created')
        batch_op.drop_index('ix_import_batches_checksum')

    op.drop_table('import_batches')
    op.drop_table('form_sections')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index('ix_attendance_work_date')

    op.drop_table('attendance')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_user_sessions_user_active')

    op.drop_table('user_sessions')
    op.drop_table('user_roles')
    op.drop_table('saved_filters')
    op.drop_table('role_permissions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read_created')

    op.drop_table('notifications')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_login_attempts_email_created')

    op.drop_table('login_attempts')
    op.drop_table('import_templates')
    with op.batch_alter_table('form_templates', schema=None) as batch_op:
        batch_op.drop_index('ix_form_templates_lookup')

    op.drop_table('form_templates')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index('ix_employees_department_designation')

    op.drop_table('employees')
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.drop_index('ix_document_templates_lookup')

    op.drop_table('document_templates')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index('ix_audit_logs_created_at')
        batch_op.drop_index('ix_audit_logs_actor_created')
        batch_op.drop_index('ix_audit_logs_action')

    op.drop_table('audit_logs')
    op.drop_table('app_settings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_last_activity_at')
        batch_op.drop_index('ix_users_is_active_staff_category')

    op.drop_table('users')
    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_module'))

    op.drop_table('permissions')
    op.drop_table('designations')
    op.drop_table('departments')
    op.drop_table('companies')
    op.drop_table('case_types')
    op.drop_table('case_number_sequences')
    # ### end Alembic commands ###
